# Generated by Django 3.1.4 on 2021-10-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211016_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pic',
            field=models.ImageField(default='avatar.svg', upload_to=''),
        ),
    ]
