# Generated by Django 3.1.4 on 2021-10-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211017_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
