# Generated by Django 3.1.4 on 2021-11-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211017_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='pic',
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
